### ISSUE TITLE
error on execution

### ISSUE THREAD

**Issue by rmi7** [MAIAN-tool/MAIAN#10]
I've installed MAIAN in a docker container using:

```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y git python software-properties-common python-software-properties \
  && add-apt-repository ppa:ethereum/ethereum \
  && apt-get update \
  && apt-get install -y ethereum solc python-pip \
  && pip install --upgrade pip \
  && pip install z3-solver z3 web3

RUN git clone https://github.com/MAIAN-tool/MAIAN.git
```

whenever I execute on a smart contract (which I've put inside the same dir as `maian.py`), I get:

```
Traceback (most recent call last):
File "maian.py", line 182, in <module>
  main(sys.argv[1:])
File "maian.py", line 85, in main
  kill_active_blockchain()
File "/MAIAN/tool/blockchain.py", line 69, in kill_active_blockchain
  p = subprocess.Popen(['fuser',MyGlobals.port_number+'/tcp'], stdout=subprocess.PIPE, stderr=devnull)
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
  errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
  raise child_exception
OSError: [Errno 2] No such file or directory
```

Am I missing some dependency?

**Comment by fmgoncalves** [comment]
You are missing a few runtime dependencies (which are installed in regular ubuntu distributions, but not in ubuntu docker containers), Just `apt install psmisc lsof` and it should work.

For the record, if you read the error message carefully, you will see that the complaint is about not being able to exec the `fuser` command.

**Comment by LoCorVin** [comment]
@rmi7 Did you ever get the docker image running?

**Comment by rmi7** [comment]
@LoCorVin working on it this afternoon, will post update later on today/tomorrow

**Comment by rmi7** [comment]
ok `web3` pip module got updated recently (version `4.x`) and now only supports `python3+`, solution is to install `web3 3.x`.

**Comment by LoCorVin** [comment]
I also succeeded in in getting the web 3 error away, but had to downgrade web3 to version 3.4.4 because of a required KeepAliveRPCProvider that was removed in the later versions of web3. With this version however the calls to sha3 couldn't be static anymore and i now have no clue which web3 version they might have used or how to change their code

**Comment by rmi7** [comment]
After having gone through all this I end up at an error related to `pandoc`. I've also been getting other `pandoc` related errors in other projects recently.

```
Collecting eth-hash<1.0.0,>=0.1.0 (from eth-utils>=0.7.1->web3==3.16.4)
  Downloading https://files.pythonhosted.org/packages/17/25/eb0af4e225bd8c2226b9296474e4bd19d1174433b22b41d5680f1dcae090/eth-hash-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__

    Installed /tmp/pip-build-W3fjbW/eth-hash/.eggs/pypandoc-1.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-W3fjbW/eth-hash/setup.py", line 71, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 372, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 528, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-W3fjbW/eth-hash/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-build-W3fjbW/eth-hash/.eggs/pypandoc-1.4-py2.7.egg/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
```

So for now I've given up on this (and the other projects that give me `pandoc` related errors). It probably will get fixed in the near future.

**Comment by 1522402210** [comment]
mac

python3 maian.py
Traceback (most recent call last):
  File "gui-maian.py", line 23, in <module>
    import maian
  File "/Users/o/MAIAN_automatictool_for_Ethereumsmartcontracts/tool/maian.py", line 24, in <module>
    from web3 import Web3, KeepAliveRPCProvider, IPCProvider
ImportError: cannot import name 'KeepAliveRPCProvider'

**Comment by faran20** [comment]
`pip3 install web3` worked for me

**Comment by treoleopi** [comment]
any updates anyone? I am now trying to fix the web3 thingy on ubuntu 16.04...
