### ISSUE TITLE
sha3() missing 1 required positional argument: 'value'

### ISSUE THREAD

**Issue by johniadeluca** [MAIAN-tool/MAIAN#22]
Getting this error after installing and adhering to all of the indicated dependencies mentioned earlier.

```
Traceback (most recent call last):
  File "maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "maian.py", line 105, in main
    fhashes = get_function_hashes( args.soliditycode[1] )
  File "/Users/johniadeluca/Desktop/logoEdits/MAIAN/tool/contracts.py", line 59, in get_function_hashes
    hash_op = Web3.sha3(hs.encode('utf-8'), encoding='bytes')
  File "/Users/johniadeluca/anaconda3/lib/python3.6/site-packages/web3/utils/string.py", line 83, in inner
    return force_obj_to_text(fn(*args, **kwargs))
TypeError: sha3() missing 1 required positional argument: 'value'
```

Any help/ideas? Can't find the declaration of sha3()

**Comment by 77aq** [comment]
met it too

**Comment by Cao-Rong** [comment]
oh,I met it too...

**Comment by Ryokocc** [comment]
I replace web3 to 3.4.4，and then met this problem....

**Comment by fabioajm** [comment]
Someone found the fix?

**Comment by Rimay** [comment]
I met the same problem, has anybody solved it???

**Comment by gsalzer** [comment]
Try the fork at https://github.com/smartbugs/MAIAN, which updates Maian to recent versions of Python3, web3 and z3.
