### ISSUE TITLE
"unknown transaction" during deploy_contract

### ISSUE THREAD

**Issue by pirapira** [MAIAN-tool/MAIAN#5]
When I try to run `run_examples`, I see several error messages.  The first error is as follows:

```
~/src/MAIAN/tool(master) $ python --version
Python 2.7.14+
~/src/MAIAN/tool(master) $ geth version
Geth
Version: 1.8.0-unstable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10
~/src/MAIAN/tool(master) $ python maian.py -s example_contracts/example_suicidal.sol KAI -c 0

====================================================================================================
[ ] Compiling Solidity contract from the file example_contracts/example_suicidal.sol ...  Done 
/usr/local/lib/python2.7/dist-packages/web3/main.py:130: DeprecationWarning: Python 2 support is ending! Please upgrade to Python 3 promptly. Support will end at the beginning of 2018.
  category=DeprecationWarning,
/usr/local/lib/python2.7/dist-packages/web3/main.py:130: DeprecationWarning: Python 2 support is ending! Please upgrade to Python 3 promptly. Support will end at the beginning of 2018.
  category=DeprecationWarning,
[ ] Connecting to PRIVATE blockchain emptychain  ... ESTABLISHED 
[ ] Deploying contract .Traceback (most recent call last):
  File "maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "maian.py", line 120, in main
    if args.soliditycode:   contract_address = deploy_contract(args.soliditycode[1], MyGlobals.etherbase_account)
  File "/home/yh/src/MAIAN/tool/contracts.py", line 99, in deploy_contract
    s.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "/home/yh/src/MAIAN/tool/contracts.py", line 115, in confirm_contract
    receipt = MyGlobals.web3.eth.getTransactionReceipt(transaction_creation_hash)
  File "/usr/local/lib/python2.7/dist-packages/web3/eth.py", line 192, in getTransactionReceipt
    [transaction_hash],
  File "/usr/local/lib/python2.7/dist-packages/web3/manager.py", line 96, in request_blocking
    raise ValueError(response["error"])
ValueError: {u'message': u'unknown transaction', u'code': -32000}
```

**Comment by max-block** [comment]
I have the same error for the first example. My env:

```
(venv) maxblock@mbp tool (master)*$ python --version
Python 3.6.4
(venv) maxblock@mbp tool (master)*$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.21+commit.dfe3193c.Darwin.appleclang
(venv) maxblock@mbp tool (master)*$ geth version
Geth
Version: 1.8.1-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: darwin
GOPATH=
GOROOT=/usr/local/opt/go/libexec
```

**Comment by hiqua** [comment]
Can you try with the latest geth version, i.e. `Version: 1.8.2-stable`?

With this version, the deployment seems to succeed, but I have other errors afterwards:

```sh
====================================================================================================
[ ] Compiling Solidity contract from the file example_contracts/example_suicidal.sol ...  Done
[ ] Connecting to PRIVATE blockchain emptychain  . ESTABLISHED
[ ] Deploying contract .... confirmed at address: 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306
[ ] Contract code length on the blockchain :    7754  : 0x6060604052600436106100d05760...
[ ] Contract address saved in file: ./out/KAI.address
[ ] Check if contract is SUICIDAL

[ ] Contract address   : 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306
[ ] Contract bytecode  : 6060604052600436106100d0576000357c0100000000000000...
[ ] Bytecode length    : 7752
[ ] Blockchain contract: True
[ ] Debug              : False

[ ] Search with call depth: 1   : Exception: 'float' object cannot be interpreted as an integer
Exception: 'float' object cannot be interpreted as an integer
11Exception: 'float' object cannot be interpreted as an integer
...
```

**Comment by pirapira** [comment]
That worked for me.  Perhaps the different geth version.
