### ISSUE TITLE
TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by makoto** [MAIAN-tool/MAIAN#8]
Hello.

I tried to run the initial example on my mac but does not seem working.

```
[~/src/MAIAN/tool -  (master)] $ python --version
Python 3.6.4
[~/src/MAIAN/tool -  (master)] $ geth version
Geth
Version: 1.8.1-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: darwin
GOPATH=
GOROOT=/usr/local/opt/go/libexec
[~/src/MAIAN/tool -  (master)] $ python maian.py -s example_contracts/ParityWalletLibrary.sol WalletLibrary -c 0

====================================================================================================
[ ] Compiling Solidity contract from the file example_contracts/ParityWalletLibrary.sol ... Traceback (most recent call last):
  File "maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "maian.py", line 98, in main
    compile_contract(args.soliditycode[0])
  File "~/src/MAIAN/tool/contracts.py", line 32, in compile_contract
    solo += l
TypeError: must be str, not bytes
```

**Comment by fccbb** [comment]
same here:

```shell
% python maian.py -s s_functionalities.sol Plentix -c 0

====================================================================================================
[ ] Compiling Solidity contract from the file s_functionalities.sol ... Traceback (most recent call last):
  File "maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "maian.py", line 98, in main
    compile_contract(args.soliditycode[0])
  File "/home/blacksheep/Documents/MAIAN-master/tool/contracts.py", line 32, in compile_contract
    solo += l
TypeError: must be str, not bytes
```

**Comment by cookedsteak** [comment]
@makoto @fccbb  I changed `sole += l` into `solo += bytes.decode(l)` in contracts.py line 32.
Also, same issue in blockchain.py line 84, `out2.find` should be `bytes.decode(out2)`.

**Comment by fccbb** [comment]
worked thank you very much @cookedsteak!
