### ISSUE TITLE
 error on running maian tools 

### ISSUE THREAD

**Issue by Akityo** [MAIAN-tool/MAIAN#9]
`[ ] The contract balance: 44   Positive balance
[ ] Check if contract is PRODIGAL

[ ] Contract address   : 0x9E536236ABF2288a7864C6A1AfaA4Cb98D464306
[ ] Contract bytecode  : 606060405260043610610062576000357c0100000000000000...
[ ] Bytecode length    : 3032
[ ] Blockchain contract: True
[ ] Debug              : False

[ ] Search with call depth: 1   : Traceback (most recent call last):
  File "./maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "./maian.py", line 143, in main
    elif 1== MyGlobals.checktype: ret = check_leak.check_one_contract_on_ether_leak(code, contract_address, MyGlobals.debug, MyGlobals.read_from_blockchain, True, fhashes)
  File "/Users/addisongarcia/BlockChain/MAIAN/tool/check_leak.py", line 105, in check_one_contract_on_ether_leak
    run_one_check( i, ops, contract_address, debug, read_from_blockchain )
  File "/Users/addisongarcia/BlockChain/MAIAN/tool/check_leak.py", line 63, in run_one_check
    clear_globals()
  File "/Users/addisongarcia/BlockChain/MAIAN/tool/values.py", line 164, in clear_globals
    MyGlobals.s = Solver()
NameError: global name 'Solver' is not defined`

any idea about this ? 

i am  newbie on python ..

**Comment by nusnikolic** [comment]
Make sure you have Z3 installed

**Comment by Akityo** [comment]
@nusnikolic  Thanks, problem solved :)
